# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7e761156fa6b9c7399ef1fe4564d52c"
application_url = "https://shareholders-jp-tutorial-downloaded.trycloudflare.com"
embedded = true
name = "product-management"
handle = "product-management-23"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shareholders-jp-tutorial-downloaded.trycloudflare.com/auth/callback",
  "https://shareholders-jp-tutorial-downloaded.trycloudflare.com/auth/shopify/callback",
  "https://shareholders-jp-tutorial-downloaded.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "product-data-management.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
